---

- name: Bootstrap cluster
  import_playbook: bootstrap.yml

- name: Install k3s on master
  import_playbook: k3s_master.yml

- name: Install k3s on worker
  import_playbook: k3s_worker.yml

- name: Install databases
  import_playbook: databases.yml