---
- hosts: k3s_rpi_master
  remote_user: pi
  become: True
  gather_facts: True

  tasks:
    - name: Install / upgrade k3s on master node
      when: not master_is_already_provisioned
      shell: "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC=\"server --bind-address 0.0.0.0\" sh -"

    - name: Get token from master
      shell: "cat /var/lib/rancher/k3s/server/node-token"
      register: k3s_node_token

    - name: Make sure destination dir exists
      become: False
      file:
        path: /home/{{ rpi_username }}/kubedeployments
        state: directory

    - name: Copy dashboard admin file
      when: not master_is_already_provisioned
      become: False
      copy:
        src: files/dashboard-admin.yaml 
        dest: /home/{{ rpi_username }}/kubedeployments/dashboard-admin.yaml
        owner: "{{ rpi_username }}"
        group: "{{ rpi_username }}"
        mode: '0644'

    - name: Apply dashboard admin
      when: not master_is_already_provisioned
      shell: "k3s kubectl apply -f /home/{{ rpi_username }}/kubedeployments/dashboard-admin.yaml"

    - name: Install dashboard
      when: not master_is_already_provisioned
      shell: "k3s kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/recommended.yaml"

    - name: Get dashboard token
      when: not master_is_already_provisioned
      shell: "k3s kubectl -n kube-system describe secret $(k3s kubectl -n kube-system get secret | grep admin-user | awk '{print $1}') | grep token: | cut -d':' -f2 | xargs"
      register: dashboard_token

    - name: Save dashboard token to credentials/dashboard_token
      when: not master_is_already_provisioned
      become: False
      local_action: copy content={{ dashboard_token.stdout }} dest={{ playbook_dir }}/credentials/dashboard_token

    - name: Download kubernetes config
      when: not master_is_already_provisioned
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ playbook_dir }}/credentials/k3s.yaml"
        flat: yes

    - name: Set correct IP in downloaded kubernetes config
      when: not master_is_already_provisioned
      become: False
      local_action: 
        module: lineinfile
        dest: "{{ playbook_dir }}/credentials/k3s.yaml"
        regexp: "^    server"
        line: "    server: https://{{ master_node_ip }}:6443"

    - name: Create .kube directory
      when: not master_is_already_provisioned
      become: False
      file:
        path: /home/{{ rpi_username }}/.kube
        state: directory

    - name: Copy kube config and fix ip
      when: not master_is_already_provisioned
      shell: "cp /etc/rancher/k3s/k3s.yaml /home/{{ rpi_username }}/.kube/config && chown {{rpi_username }}:{{ rpi_username }} /home/{{ rpi_username }}/.kube/config && sed -i -e 's/[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}/127.0.0.1/g' /home/{{ rpi_username }}/.kube/config"

    - name: Clone OpenFAAS kubernetes charts
      when: not master_is_already_provisioned
      become: False
      git:
        repo: https://github.com/openfaas/faas-netes.git
        dest: /home/{{ rpi_username }}/faas-netes

    - name: Install OpenFAAS
      when: not master_is_already_provisioned
      shell: |
        k3s kubectl apply -f /home/{{ rpi_username }}/faas-netes/namespaces.yml
        k3s kubectl apply -f /home/{{ rpi_username }}/faas-netes/yaml_armhf

