# Use python3
ansible_python_interpreter: /usr/bin/python3 
 
# Defines jumphost IP address to use as bastion host to reach isolated hosts
master_node_name: "{{ groups['k3s_rpi_master'][0] }}"
master_node_ip: "{{ hostvars[master_node_name].ansible_host }}"
 
# Default raspberry pi login
rpi_username: pi
rpi_password: raspberry
 
# Defines the ansible user to use when connecting to devices
ansible_user: "{{ rpi_username }}"
 
# Defines the ansible password to use when connecting to devices
ansible_password: "{{ rpi_password }}"

# Defines if the raspberry's needs to be secured (change pass, remove ssh-pass access, ...) or not
do_secure: false

# Defines if the master-node is already provisioned. If that is the case only the worker nodes are configured
# Can be used to add further worker to the cluster
# ToDo: let an task decide if the master is already provisioned
master_is_already_provisioned: true